server.port=8081
spring.application.name=peliculas-microservicio

# ============================================================
# CONFIGURACION BASE DE DATOS ORACLE AUTONOMOUS (OCI - Santiago)
# Wallet ubicado en: src/main/resources/wallet
# ============================================================
spring.datasource.url=jdbc:oracle:thin:@admin_medium
spring.datasource.hikari.data-source-properties.oracle.net.tns_admin=/Users/isamar.reyes/Desktop/Isamarita Duoc/PROYECTOS/pelicula-tarea-/src/main/resources/wallet
spring.datasource.hikari.data-source-properties.oracle.net.wallet_location=(SOURCE=(METHOD=FILE)(METHOD_DATA=(DIRECTORY=/Users/isamar.reyes/Desktop/Isamarita Duoc/PROYECTOS/pelicula-tarea-/src/main/resources/wallet)))
spring.datasource.username=BDY2201_PELI001
spring.datasource.password=ClaveSegura_2024!
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# ============================================================
# CONFIGURACION JPA / HIBERNATE
# ============================================================
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.properties.hibernate.id.new_generator_mappings=true

# Logs
logging.level.com.duoc.peliculas=DEBUG